sudo: required
dist: trusty

language: node_js
node_js:
  - "12"
  - "10"

addons:
  chrome: stable

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

cache:
  directories:
    - ./node_modules

install:
  - npm install
  - npm rebuild

script:
  - npm run test-lib -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
